window.MASTER_DATA = {
  "generatedFrom": "emploi-du-temps_tous-les-filtres (4) (1).xlsx",
  "rooms": [
    "S 04",
    "S 05",
    "S 06",
    "S 07",
    "S 08",
    "S 09",
    "S 10",
    "S 11",
    "S 13",
    "S 14",
    "S 15",
    "S 16",
    "S 17",
    "S 18",
    "S 19",
    "S 20",
    "S 21",
    "S 22",
    "S 23",
    "S 24",
    "S 25",
    "S 26",
    "S 27",
    "AMPHI A",
    "AMPHI B",
    "SC 01",
    "SC 02",
    "TP 01",
    "TP 02",
    "TP 03",
    "TP 04"
  ],
  "sessions": [
    {
      "id": "S0001",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": null,
      "audience": "Section 01",
      "day": "Saturday",
      "time": "08:30-10:00",
      "module": "Comptabilité Financière",
      "type": "Cours",
      "professor": "Belloula Akram",
      "room": "AMPHI A"
    },
    {
      "id": "S0002",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": null,
      "audience": "Section 01",
      "day": "Saturday",
      "time": "10:00-11:30",
      "module": "Économie générale",
      "type": "Cours",
      "professor": "Tchikou Faouzi",
      "room": "AMPHI A"
    },
    {
      "id": "S0003",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": null,
      "audience": "Section 01",
      "day": "Saturday",
      "time": "13:00-14:30",
      "module": "Philosophie",
      "type": "Cours",
      "professor": "Chennafi Mohamed",
      "room": "AMPHI A"
    },
    {
      "id": "S0004",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": null,
      "audience": "Section 01",
      "day": "Saturday",
      "time": "14:30-16:00",
      "module": "Fondement du droit 1",
      "type": "Cours",
      "professor": "El-mahi Fatima Zohra Cherifa",
      "room": "AMPHI A"
    },
    {
      "id": "S0005",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 01",
      "audience": "Section 01 · Group 01",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "BRAHAMI Samira",
      "room": "S 04"
    },
    {
      "id": "S0006",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 01",
      "audience": "Section 01 · Group 01",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Khelloui Nassima",
      "room": "S 19"
    },
    {
      "id": "S0007",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": null,
      "audience": "Section 01",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Algèbre",
      "type": "Cours",
      "professor": "Salhi Khedidja",
      "room": "AMPHI A"
    },
    {
      "id": "S0008",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": null,
      "audience": "Section 01",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 1",
      "type": "Cours",
      "professor": "Naceri Mostepha",
      "room": "AMPHI A"
    },
    {
      "id": "S0009",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": null,
      "audience": "Section 01",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Statistiques",
      "type": "Cours",
      "professor": "Boulanouar",
      "room": "AMPHI A"
    },
    {
      "id": "S0010",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": null,
      "audience": "Section 01",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Histoire de l'Algérie",
      "type": "Cours",
      "professor": "Khedim Tarek",
      "room": "SC 01"
    },
    {
      "id": "S0011",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 01",
      "audience": "Section 01 · Group 01",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Fellah",
      "room": "TP 01"
    },
    {
      "id": "S0012",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 01",
      "audience": "Section 01 · Group 01",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Chentouf",
      "room": "S 08"
    },
    {
      "id": "S0013",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 01",
      "audience": "Section 01 · Group 01",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Henni",
      "room": "S 08"
    },
    {
      "id": "S0014",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 01",
      "audience": "Section 01 · Group 01",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Belgharsa Nor Elhouda",
      "room": "S 04"
    },
    {
      "id": "S0015",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 01",
      "audience": "Section 01 · Group 01",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Zaarat Ahlem",
      "room": "S 04"
    },
    {
      "id": "S0016",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 02",
      "audience": "Section 01 · Group 02",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Remili Omar El Houari",
      "room": "S 16"
    },
    {
      "id": "S0017",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 02",
      "audience": "Section 01 · Group 02",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Elmogherbi Salima",
      "room": "S 05"
    },
    {
      "id": "S0018",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 02",
      "audience": "Section 01 · Group 02",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Hirech Nawal",
      "room": "S 09"
    },
    {
      "id": "S0019",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 02",
      "audience": "Section 01 · Group 02",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Fellah",
      "room": "TP 01"
    },
    {
      "id": "S0020",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 02",
      "audience": "Section 01 · Group 02",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Chellali Cherifa",
      "room": "S 11"
    },
    {
      "id": "S0021",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 02",
      "audience": "Section 01 · Group 02",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Chentouf",
      "room": "S 05"
    },
    {
      "id": "S0022",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 02",
      "audience": "Section 01 · Group 02",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Douar",
      "room": "S 05"
    },
    {
      "id": "S0023",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 03",
      "audience": "Section 01 · Group 03",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Khelloui Nassima",
      "room": "S 06"
    },
    {
      "id": "S0024",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 03",
      "audience": "Section 01 · Group 03",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Remili Omar El Houari",
      "room": "S 06"
    },
    {
      "id": "S0025",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 03",
      "audience": "Section 01 · Group 03",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Bendoukha Fatima",
      "room": "S 04"
    },
    {
      "id": "S0026",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 03",
      "audience": "Section 01 · Group 03",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Bouzaghou Asmaa",
      "room": "S 04"
    },
    {
      "id": "S0027",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 03",
      "audience": "Section 01 · Group 03",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Salhi Khedidja",
      "room": "S 04"
    },
    {
      "id": "S0028",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 03",
      "audience": "Section 01 · Group 03",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "KACI Nadjet",
      "room": "S 06"
    },
    {
      "id": "S0029",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 03",
      "audience": "Section 01 · Group 03",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Djebbar Nacera",
      "room": "TP 01"
    },
    {
      "id": "S0030",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 04",
      "audience": "Section 01 · Group 04",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Elmogherbi Salima",
      "room": "S 07"
    },
    {
      "id": "S0031",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 04",
      "audience": "Section 01 · Group 04",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "BRAHAMI Samira",
      "room": "S 07"
    },
    {
      "id": "S0032",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 04",
      "audience": "Section 01 · Group 04",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Salhi Khedidja",
      "room": "S 07"
    },
    {
      "id": "S0033",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 04",
      "audience": "Section 01 · Group 04",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "MEZIANE Amine",
      "room": "TP 02"
    },
    {
      "id": "S0034",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 04",
      "audience": "Section 01 · Group 04",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Remili Omar El Houari",
      "room": "S 07"
    },
    {
      "id": "S0035",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 04",
      "audience": "Section 01 · Group 04",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Bouzaghou Asmaa",
      "room": "S 07"
    },
    {
      "id": "S0036",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 04",
      "audience": "Section 01 · Group 04",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "KACI Nadjet",
      "room": "S 07"
    },
    {
      "id": "S0037",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 05",
      "audience": "Section 01 · Group 05",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Soulimane Nesrine",
      "room": "S 08"
    },
    {
      "id": "S0038",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 05",
      "audience": "Section 01 · Group 05",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Bendoukha Fatima",
      "room": "S 08"
    },
    {
      "id": "S0039",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 05",
      "audience": "Section 01 · Group 05",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Salhi Khedidja",
      "room": "S 05"
    },
    {
      "id": "S0040",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 05",
      "audience": "Section 01 · Group 05",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Hirech Nawal",
      "room": "S 05"
    },
    {
      "id": "S0041",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 05",
      "audience": "Section 01 · Group 05",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Remili Omar El Houari",
      "room": "S 05"
    },
    {
      "id": "S0042",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 05",
      "audience": "Section 01 · Group 05",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Zeddam",
      "room": "S 05"
    },
    {
      "id": "S0043",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 05",
      "audience": "Section 01 · Group 05",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Boubekki",
      "room": "TP 02"
    },
    {
      "id": "S0044",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 06",
      "audience": "Section 01 · Group 06",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Soulimane Nesrine",
      "room": "S 08"
    },
    {
      "id": "S0045",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 06",
      "audience": "Section 01 · Group 06",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "BRAHAMI Samira",
      "room": "S 11"
    },
    {
      "id": "S0046",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 06",
      "audience": "Section 01 · Group 06",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Djebbar Nacera",
      "room": "TP 03"
    },
    {
      "id": "S0047",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 06",
      "audience": "Section 01 · Group 06",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Salhi Khedidja",
      "room": "S 06"
    },
    {
      "id": "S0048",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 06",
      "audience": "Section 01 · Group 06",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Zeddam",
      "room": "S 06"
    },
    {
      "id": "S0049",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 06",
      "audience": "Section 01 · Group 06",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Henni",
      "room": "S 08"
    },
    {
      "id": "S0050",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 01",
      "group": "Group 06",
      "audience": "Section 01 · Group 06",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Belgharsa Nor Elhouda",
      "room": "S 08"
    },
    {
      "id": "S0051",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": null,
      "audience": "Section 02",
      "day": "Saturday",
      "time": "08:30-10:00",
      "module": "Économie générale",
      "type": "Cours",
      "professor": "Tchikou Faouzi",
      "room": "AMPHI B"
    },
    {
      "id": "S0052",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 07",
      "audience": "Section 02 · Group 07",
      "day": "Saturday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Zaarat Ahlem",
      "room": "S 06"
    },
    {
      "id": "S0053",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": null,
      "audience": "Section 02",
      "day": "Saturday",
      "time": "13:00-14:30",
      "module": "Fondement du droit 1",
      "type": "Cours",
      "professor": "El-mahi Fatima Zohra Cherifa",
      "room": "AMPHI B"
    },
    {
      "id": "S0054",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": null,
      "audience": "Section 02",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Comptabilité Financière",
      "type": "Cours",
      "professor": "Belhadj Ahmed Nadjia",
      "room": "AMPHI A"
    },
    {
      "id": "S0055",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": null,
      "audience": "Section 02",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Algèbre",
      "type": "Cours",
      "professor": "Chellali Cherifa",
      "room": "AMPHI A"
    },
    {
      "id": "S0056",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 07",
      "audience": "Section 02 · Group 07",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Hirech Nawal",
      "room": "S 05"
    },
    {
      "id": "S0057",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 07",
      "audience": "Section 02 · Group 07",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Algèbre",
      "type": "Td",
      "professor": "MATH 1",
      "room": "S 13"
    },
    {
      "id": "S0058",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": null,
      "audience": "Section 02",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Statistiques",
      "type": "Cours",
      "professor": "Boulanouar",
      "room": "AMPHI B"
    },
    {
      "id": "S0059",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": null,
      "audience": "Section 02",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Analyse mathématiques 1",
      "type": "Cours",
      "professor": "Bouteraa",
      "room": "AMPHI A"
    },
    {
      "id": "S0060",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": null,
      "audience": "Section 02",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Philosophie",
      "type": "Cours",
      "professor": "Chennafi Mohamed",
      "room": "AMPHI A"
    },
    {
      "id": "S0061",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 07",
      "audience": "Section 02 · Group 07",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Bendoukha Fatima",
      "room": "S 09"
    },
    {
      "id": "S0062",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 07",
      "audience": "Section 02 · Group 07",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Chentouf",
      "room": "S 09"
    },
    {
      "id": "S0063",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 07",
      "audience": "Section 02 · Group 07",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "DJEBBAR Amel Mounia",
      "room": "TP 01"
    },
    {
      "id": "S0064",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": null,
      "audience": "Section 02",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Histoire de l'Algérie",
      "type": "Cours",
      "professor": "Khedim Tarek",
      "room": "SC 01"
    },
    {
      "id": "S0065",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 07",
      "audience": "Section 02 · Group 07",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Cherifi Asmaa",
      "room": "S 10"
    },
    {
      "id": "S0066",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 08",
      "audience": "Section 02 · Group 08",
      "day": "Saturday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Belgharsa Nor Elhouda",
      "room": "S 07"
    },
    {
      "id": "S0067",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 08",
      "audience": "Section 02 · Group 08",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Bendoukha Fatima",
      "room": "S 19"
    },
    {
      "id": "S0068",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 08",
      "audience": "Section 02 · Group 08",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Djaafri",
      "room": "S 06"
    },
    {
      "id": "S0069",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 08",
      "audience": "Section 02 · Group 08",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Dekkiche",
      "room": "S 10"
    },
    {
      "id": "S0070",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 08",
      "audience": "Section 02 · Group 08",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Djebbar Nacera",
      "room": "TP 03"
    },
    {
      "id": "S0071",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 08",
      "audience": "Section 02 · Group 08",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Chellali Cherifa",
      "room": "S 11"
    },
    {
      "id": "S0072",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 08",
      "audience": "Section 02 · Group 08",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Bouzaghou Asmaa",
      "room": "S 06"
    },
    {
      "id": "S0073",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 09",
      "audience": "Section 02 · Group 09",
      "day": "Saturday",
      "time": "14:30-16:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Zaarat Ahlem",
      "room": "S 06"
    },
    {
      "id": "S0074",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 09",
      "audience": "Section 02 · Group 09",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Djaafri",
      "room": "S 07"
    },
    {
      "id": "S0075",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 09",
      "audience": "Section 02 · Group 09",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Khelloui Nassima",
      "room": "S 06"
    },
    {
      "id": "S0076",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 09",
      "audience": "Section 02 · Group 09",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Douar",
      "room": "S 06"
    },
    {
      "id": "S0077",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 09",
      "audience": "Section 02 · Group 09",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "MEZIANE Amine",
      "room": "TP 02"
    },
    {
      "id": "S0078",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 09",
      "audience": "Section 02 · Group 09",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Soulimane Nesrine",
      "room": "S 16"
    },
    {
      "id": "S0079",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 09",
      "audience": "Section 02 · Group 09",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Salhi Khedidja",
      "room": "S 16"
    },
    {
      "id": "S0080",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 10",
      "audience": "Section 02 · Group 10",
      "day": "Saturday",
      "time": "10:00-11:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Kemmar",
      "room": "TP 01"
    },
    {
      "id": "S0081",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 10",
      "audience": "Section 02 · Group 10",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Argillos Amel",
      "room": "S 08"
    },
    {
      "id": "S0082",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 10",
      "audience": "Section 02 · Group 10",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Bouanani Ismahene",
      "room": "S 15"
    },
    {
      "id": "S0083",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 10",
      "audience": "Section 02 · Group 10",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Remili Omar El Houari",
      "room": "S 07"
    },
    {
      "id": "S0084",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 10",
      "audience": "Section 02 · Group 10",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Chellali Cherifa",
      "room": "S 11"
    },
    {
      "id": "S0085",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 10",
      "audience": "Section 02 · Group 10",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Hirech Nawal",
      "room": "S 07"
    },
    {
      "id": "S0086",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 10",
      "audience": "Section 02 · Group 10",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Chentouf",
      "room": "S 09"
    },
    {
      "id": "S0087",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 11",
      "audience": "Section 02 · Group 11",
      "day": "Saturday",
      "time": "10:00-11:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "MATH 2",
      "room": "S 08"
    },
    {
      "id": "S0088",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 11",
      "audience": "Section 02 · Group 11",
      "day": "Saturday",
      "time": "14:30-16:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Belgharsa Nor Elhouda",
      "room": "S 08"
    },
    {
      "id": "S0089",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 11",
      "audience": "Section 02 · Group 11",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Cherifi Asmaa",
      "room": "S 09"
    },
    {
      "id": "S0090",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 11",
      "audience": "Section 02 · Group 11",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Kemmar",
      "room": "TP 01"
    },
    {
      "id": "S0091",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 11",
      "audience": "Section 02 · Group 11",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Chentouf",
      "room": "S 08"
    },
    {
      "id": "S0092",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 11",
      "audience": "Section 02 · Group 11",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Maamar",
      "room": "S 17"
    },
    {
      "id": "S0093",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 11",
      "audience": "Section 02 · Group 11",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Douar",
      "room": "S 17"
    },
    {
      "id": "S0094",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 12",
      "audience": "Section 02 · Group 12",
      "day": "Saturday",
      "time": "10:00-11:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "MATH 1",
      "room": "S 09"
    },
    {
      "id": "S0095",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 12",
      "audience": "Section 02 · Group 12",
      "day": "Saturday",
      "time": "14:30-16:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Elfour Karima",
      "room": "S 09"
    },
    {
      "id": "S0096",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 12",
      "audience": "Section 02 · Group 12",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Hiber",
      "room": "S 10"
    },
    {
      "id": "S0097",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 12",
      "audience": "Section 02 · Group 12",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "BRAHAMI Samira",
      "room": "S 07"
    },
    {
      "id": "S0098",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 12",
      "audience": "Section 02 · Group 12",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Khelloui Nassima",
      "room": "S 13"
    },
    {
      "id": "S0099",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 12",
      "audience": "Section 02 · Group 12",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Henni",
      "room": "S 13"
    },
    {
      "id": "S0100",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 02",
      "group": "Group 12",
      "audience": "Section 02 · Group 12",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Djebbar Nacera",
      "room": "TP 03"
    },
    {
      "id": "S0101",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": null,
      "audience": "Section 03",
      "day": "Saturday",
      "time": "10:00-11:30",
      "module": "Comptabilité Financière",
      "type": "Cours",
      "professor": "Belloula Akram",
      "room": "AMPHI B"
    },
    {
      "id": "S0102",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 13",
      "audience": "Section 03 · Group 13",
      "day": "Saturday",
      "time": "13:00-14:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "MATH 2",
      "room": "S 08"
    },
    {
      "id": "S0103",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": null,
      "audience": "Section 03",
      "day": "Saturday",
      "time": "14:30-16:00",
      "module": "Philosophie",
      "type": "Cours",
      "professor": "Chennafi Mohamed",
      "room": "AMPHI B"
    },
    {
      "id": "S0104",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": null,
      "audience": "Section 03",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Algèbre",
      "type": "Cours",
      "professor": "Chellali Cherifa",
      "room": "AMPHI B"
    },
    {
      "id": "S0105",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": null,
      "audience": "Section 03",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Fondement du droit 1",
      "type": "Cours",
      "professor": "El-mahi Fatima Zohra Cherifa",
      "room": "AMPHI B"
    },
    {
      "id": "S0106",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 13",
      "audience": "Section 03 · Group 13",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Hiber",
      "room": "S 10"
    },
    {
      "id": "S0107",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 13",
      "audience": "Section 03 · Group 13",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Khelloui Nassima",
      "room": "S 06"
    },
    {
      "id": "S0108",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": null,
      "audience": "Section 03",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 1",
      "type": "Cours",
      "professor": "Naceri Mostepha",
      "room": "AMPHI B"
    },
    {
      "id": "S0109",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": null,
      "audience": "Section 03",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Statistiques",
      "type": "Cours",
      "professor": "Boulanouar",
      "room": "AMPHI B"
    },
    {
      "id": "S0110",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": null,
      "audience": "Section 03",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Économie générale",
      "type": "Cours",
      "professor": "Tchikou Faouzi",
      "room": "AMPHI B"
    },
    {
      "id": "S0111",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 13",
      "audience": "Section 03 · Group 13",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Soulimane Nesrine",
      "room": "S 17"
    },
    {
      "id": "S0112",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 13",
      "audience": "Section 03 · Group 13",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Douar",
      "room": "S 14"
    },
    {
      "id": "S0113",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 13",
      "audience": "Section 03 · Group 13",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Hirech Nawal",
      "room": "S 14"
    },
    {
      "id": "S0114",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 13",
      "audience": "Section 03 · Group 13",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Djebbar Nacera",
      "room": "TP 01"
    },
    {
      "id": "S0115",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": null,
      "audience": "Section 03",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Histoire de l'Algérie",
      "type": "Cours",
      "professor": "Khedim Tarek",
      "room": "SC 01"
    },
    {
      "id": "S0116",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 14",
      "audience": "Section 03 · Group 14",
      "day": "Saturday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Zaarat Ahlem",
      "room": "S 06"
    },
    {
      "id": "S0117",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 14",
      "audience": "Section 03 · Group 14",
      "day": "Saturday",
      "time": "13:00-14:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "Zaarat Ahlem",
      "room": "S 06"
    },
    {
      "id": "S0118",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 14",
      "audience": "Section 03 · Group 14",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Kemmar",
      "room": "TP 01"
    },
    {
      "id": "S0119",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 14",
      "audience": "Section 03 · Group 14",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Henni",
      "room": "S 09"
    },
    {
      "id": "S0120",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 14",
      "audience": "Section 03 · Group 14",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Douar",
      "room": "S 14"
    },
    {
      "id": "S0121",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 14",
      "audience": "Section 03 · Group 14",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Bouzaghou Asmaa",
      "room": "S 10"
    },
    {
      "id": "S0122",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 14",
      "audience": "Section 03 · Group 14",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Cherifi Asmaa",
      "room": "S 10"
    },
    {
      "id": "S0123",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 15",
      "audience": "Section 03 · Group 15",
      "day": "Saturday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Belgharsa Nor Elhouda",
      "room": "S 07"
    },
    {
      "id": "S0124",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 15",
      "audience": "Section 03 · Group 15",
      "day": "Saturday",
      "time": "13:00-14:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "MATH 1",
      "room": "S 07"
    },
    {
      "id": "S0125",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 15",
      "audience": "Section 03 · Group 15",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "BRAHAMI Samira",
      "room": "S 11"
    },
    {
      "id": "S0126",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 15",
      "audience": "Section 03 · Group 15",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Bouzaghou Asmaa",
      "room": "S 15"
    },
    {
      "id": "S0127",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 15",
      "audience": "Section 03 · Group 15",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Zeddam",
      "room": "S 15"
    },
    {
      "id": "S0128",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 15",
      "audience": "Section 03 · Group 15",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "DJEBBAR Amel Mounia",
      "room": "TP 01"
    },
    {
      "id": "S0129",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 15",
      "audience": "Section 03 · Group 15",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Maamar",
      "room": "S 04"
    },
    {
      "id": "S0130",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 16",
      "audience": "Section 03 · Group 16",
      "day": "Saturday",
      "time": "08:30-10:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Kemmar",
      "room": "TP 01"
    },
    {
      "id": "S0131",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 16",
      "audience": "Section 03 · Group 16",
      "day": "Saturday",
      "time": "13:00-14:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Belgharsa Nor Elhouda",
      "room": "S 09"
    },
    {
      "id": "S0132",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 16",
      "audience": "Section 03 · Group 16",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Algèbre",
      "type": "Td",
      "professor": "MATH 1",
      "room": "S 17"
    },
    {
      "id": "S0133",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 16",
      "audience": "Section 03 · Group 16",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Cherifi Asmaa",
      "room": "S 17"
    },
    {
      "id": "S0134",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 16",
      "audience": "Section 03 · Group 16",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Soulimane Nesrine",
      "room": "S 16"
    },
    {
      "id": "S0135",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 16",
      "audience": "Section 03 · Group 16",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "KACI Nadjet",
      "room": "S 16"
    },
    {
      "id": "S0136",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 16",
      "audience": "Section 03 · Group 16",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Douar",
      "room": "S 11"
    },
    {
      "id": "S0137",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 17",
      "audience": "Section 03 · Group 17",
      "day": "Saturday",
      "time": "08:30-10:00",
      "module": "Algèbre",
      "type": "Td",
      "professor": "MATH 2",
      "room": "S 08"
    },
    {
      "id": "S0138",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 17",
      "audience": "Section 03 · Group 17",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Argillos Amel",
      "room": "S 19"
    },
    {
      "id": "S0139",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 17",
      "audience": "Section 03 · Group 17",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Économie générale",
      "type": "Td",
      "professor": "KACI Nadjet",
      "room": "S 14"
    },
    {
      "id": "S0140",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 17",
      "audience": "Section 03 · Group 17",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Djebbar Nacera",
      "room": "TP 03"
    },
    {
      "id": "S0141",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 17",
      "audience": "Section 03 · Group 17",
      "day": "Tuesday",
      "time": "13:00-14:30",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "Bendoukha Fatima",
      "room": "S 15"
    },
    {
      "id": "S0142",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 17",
      "audience": "Section 03 · Group 17",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Chentouf",
      "room": "S 15"
    },
    {
      "id": "S0143",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 17",
      "audience": "Section 03 · Group 17",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Zaarat Ahlem",
      "room": "S 13"
    },
    {
      "id": "S0144",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 18",
      "audience": "Section 03 · Group 18",
      "day": "Saturday",
      "time": "08:30-10:00",
      "module": "Algèbre",
      "type": "Td",
      "professor": "MATH 1",
      "room": "S 09"
    },
    {
      "id": "S0145",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 18",
      "audience": "Section 03 · Group 18",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Analyse mathématiques 1",
      "type": "Td",
      "professor": "Remili Omar El Houari",
      "room": "S 13"
    },
    {
      "id": "S0146",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 18",
      "audience": "Section 03 · Group 18",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Anglais 1",
      "type": "Td",
      "professor": "BRAHAMI Samira",
      "room": "S 07"
    },
    {
      "id": "S0147",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 18",
      "audience": "Section 03 · Group 18",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Statistiques",
      "type": "Td",
      "professor": "Khelloui Nassima",
      "room": "S 18"
    },
    {
      "id": "S0148",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 18",
      "audience": "Section 03 · Group 18",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Économie générale",
      "type": "Td",
      "professor": "Henni",
      "room": "S 18"
    },
    {
      "id": "S0149",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 18",
      "audience": "Section 03 · Group 18",
      "day": "Tuesday",
      "time": "14:30-16:00",
      "module": "Comptabilité Financière",
      "type": "Td",
      "professor": "Soulimane Nesrine",
      "room": "S 06"
    },
    {
      "id": "S0150",
      "level": "First Year Preparatory Cycle",
      "semester": "Semester 1",
      "section": "Section 03",
      "group": "Group 18",
      "audience": "Section 03 · Group 18",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Informatique 1",
      "type": "Tp",
      "professor": "Boubekki",
      "room": "TP 02"
    },
    {
      "id": "S0151",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 19",
      "audience": "Section 04 · Group 19",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Hakiki Saliha",
      "room": "TP 01"
    },
    {
      "id": "S0152",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 19",
      "audience": "Section 04 · Group 19",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Alloune Amina",
      "room": "S 04"
    },
    {
      "id": "S0153",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 19",
      "audience": "Section 04 · Group 19",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Hammouche",
      "room": "S 14"
    },
    {
      "id": "S0154",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 19",
      "audience": "Section 04 · Group 19",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "Rouane Sara",
      "room": "S 14"
    },
    {
      "id": "S0155",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 19",
      "audience": "Section 04 · Group 19",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Delhoum Sabrina Zahra",
      "room": "S 08"
    },
    {
      "id": "S0156",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 19",
      "audience": "Section 04 · Group 19",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Merras Mohammed",
      "room": "S 08"
    },
    {
      "id": "S0157",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 19",
      "audience": "Section 04 · Group 19",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Français 3",
      "type": "Td",
      "professor": "Mokhtari Latifa",
      "room": "S 16"
    },
    {
      "id": "S0158",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 19",
      "audience": "Section 04 · Group 19",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Oudjedi Damerdji Linda Fatima",
      "room": "S 16"
    },
    {
      "id": "S0159",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": null,
      "audience": "Section 04",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 3",
      "type": "Cours",
      "professor": "Oudjedi Damerdji Linda Fatima",
      "room": "AMPHI A"
    },
    {
      "id": "S0160",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": null,
      "audience": "Section 04",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Algèbre 3",
      "type": "Cours",
      "professor": "Zerkouk Hanene",
      "room": "AMPHI A"
    },
    {
      "id": "S0161",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": null,
      "audience": "Section 04",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Analyse financière",
      "type": "Cours",
      "professor": "Boukssassa Souhila Kheira",
      "room": "AMPHI A"
    },
    {
      "id": "S0162",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": null,
      "audience": "Section 04",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Probabilités 2",
      "type": "Cours",
      "professor": "Mostafa Hanchour Kheira",
      "room": "AMPHI A"
    },
    {
      "id": "S0163",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": null,
      "audience": "Section 04",
      "day": "Thursday",
      "time": "08:30-10:00",
      "module": "Microéconomie 1",
      "type": "Cours",
      "professor": "Saidi Mohammed",
      "room": "AMPHI A"
    },
    {
      "id": "S0164",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": null,
      "audience": "Section 04",
      "day": "Thursday",
      "time": "10:00-11:30",
      "module": "Géographie économique",
      "type": "Cours",
      "professor": "Benamira Nouara",
      "room": "AMPHI A"
    },
    {
      "id": "S0165",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 20",
      "audience": "Section 04 · Group 20",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Madouri Souad",
      "room": "TP 02"
    },
    {
      "id": "S0166",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 20",
      "audience": "Section 04 · Group 20",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Djemai Samira",
      "room": "S 16"
    },
    {
      "id": "S0167",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 20",
      "audience": "Section 04 · Group 20",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Alloune Amina",
      "room": "S 16"
    },
    {
      "id": "S0168",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 20",
      "audience": "Section 04 · Group 20",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Hammouche",
      "room": "S 16"
    },
    {
      "id": "S0169",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 20",
      "audience": "Section 04 · Group 20",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Français 3",
      "type": "Td",
      "professor": "Belkacem Fatima Zohra",
      "room": "S 09"
    },
    {
      "id": "S0170",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 20",
      "audience": "Section 04 · Group 20",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Mostafa Hanchour Kheira",
      "room": "S 09"
    },
    {
      "id": "S0171",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 20",
      "audience": "Section 04 · Group 20",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Oudjedi Damerdji Linda Fatima",
      "room": "S 09"
    },
    {
      "id": "S0172",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 20",
      "audience": "Section 04 · Group 20",
      "day": "Wednesday",
      "time": "14:30-16:00",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "Benamara Dalila",
      "room": "S 05"
    },
    {
      "id": "S0173",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 21",
      "audience": "Section 04 · Group 21",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "MERKIK",
      "room": "S 11"
    },
    {
      "id": "S0174",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 21",
      "audience": "Section 04 · Group 21",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Hakiki Saliha",
      "room": "TP 01"
    },
    {
      "id": "S0175",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 21",
      "audience": "Section 04 · Group 21",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "MATH 1",
      "room": "S 10"
    },
    {
      "id": "S0176",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 21",
      "audience": "Section 04 · Group 21",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Saidi Mohammed",
      "room": "S 10"
    },
    {
      "id": "S0177",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 21",
      "audience": "Section 04 · Group 21",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Khelil Chahine",
      "room": "S 10"
    },
    {
      "id": "S0178",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 21",
      "audience": "Section 04 · Group 21",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Français 3",
      "type": "Td",
      "professor": "Mokhtari Latifa",
      "room": "S 10"
    },
    {
      "id": "S0179",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 21",
      "audience": "Section 04 · Group 21",
      "day": "Wednesday",
      "time": "13:00-14:30",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Amir Samir",
      "room": "S 04"
    },
    {
      "id": "S0180",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 21",
      "audience": "Section 04 · Group 21",
      "day": "Wednesday",
      "time": "14:30-16:00",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Abdellah",
      "room": "S 04"
    },
    {
      "id": "S0181",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 22",
      "audience": "Section 04 · Group 22",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Madouri Souad",
      "room": "TP 02"
    },
    {
      "id": "S0182",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 22",
      "audience": "Section 04 · Group 22",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Delhoum Sabrina Zahra",
      "room": "S 15"
    },
    {
      "id": "S0183",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 22",
      "audience": "Section 04 · Group 22",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "MATH 2",
      "room": "S 15"
    },
    {
      "id": "S0184",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 22",
      "audience": "Section 04 · Group 22",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Hammouche",
      "room": "S 11"
    },
    {
      "id": "S0185",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 22",
      "audience": "Section 04 · Group 22",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Français 3",
      "type": "Td",
      "professor": "Belkacem Fatima Zohra",
      "room": "S 11"
    },
    {
      "id": "S0186",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 22",
      "audience": "Section 04 · Group 22",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Merras Mohammed",
      "room": "S 11"
    },
    {
      "id": "S0187",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 22",
      "audience": "Section 04 · Group 22",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Khelil Ikram",
      "room": "S 11"
    },
    {
      "id": "S0188",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 22",
      "audience": "Section 04 · Group 22",
      "day": "Wednesday",
      "time": "14:30-16:00",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "Blaha",
      "room": "S 08"
    },
    {
      "id": "S0189",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 23",
      "audience": "Section 04 · Group 23",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Alloune Amina",
      "room": "S 10"
    },
    {
      "id": "S0190",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 23",
      "audience": "Section 04 · Group 23",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Bouteraa",
      "room": "S 10"
    },
    {
      "id": "S0191",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 23",
      "audience": "Section 04 · Group 23",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "MERKIK",
      "room": "S 04"
    },
    {
      "id": "S0192",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 23",
      "audience": "Section 04 · Group 23",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Madouri Souad",
      "room": "TP 02"
    },
    {
      "id": "S0193",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 23",
      "audience": "Section 04 · Group 23",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Derouiche",
      "room": "S 04"
    },
    {
      "id": "S0194",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 23",
      "audience": "Section 04 · Group 23",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Delhoum Sabrina Zahra",
      "room": "S 04"
    },
    {
      "id": "S0195",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 23",
      "audience": "Section 04 · Group 23",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Français 3",
      "type": "Td",
      "professor": "Belkacem Fatima Zohra",
      "room": "S 04"
    },
    {
      "id": "S0196",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 23",
      "audience": "Section 04 · Group 23",
      "day": "Wednesday",
      "time": "14:30-16:00",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Amir Samir",
      "room": "S 06"
    },
    {
      "id": "S0197",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 24",
      "audience": "Section 04 · Group 24",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Delhoum Sabrina Zahra",
      "room": "S 13"
    },
    {
      "id": "S0198",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 24",
      "audience": "Section 04 · Group 24",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Hammouche",
      "room": "S 13"
    },
    {
      "id": "S0199",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 24",
      "audience": "Section 04 · Group 24",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Français 3",
      "type": "Td",
      "professor": "Mokhtari Latifa",
      "room": "S 18"
    },
    {
      "id": "S0200",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 24",
      "audience": "Section 04 · Group 24",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Bouteraa",
      "room": "S 18"
    },
    {
      "id": "S0201",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 24",
      "audience": "Section 04 · Group 24",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Hakiki Saliha",
      "room": "TP 02"
    },
    {
      "id": "S0202",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 24",
      "audience": "Section 04 · Group 24",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Zerkouk Hanene",
      "room": "S 14"
    },
    {
      "id": "S0203",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 24",
      "audience": "Section 04 · Group 24",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Djemai Samira",
      "room": "S 14"
    },
    {
      "id": "S0204",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 04",
      "group": "Group 24",
      "audience": "Section 04 · Group 24",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "Halima Rahim",
      "room": "S 14"
    },
    {
      "id": "S0205",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 25",
      "audience": "Section 05 · Group 25",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Français 3",
      "type": "Td",
      "professor": "Mokhtari Latifa",
      "room": "S 14"
    },
    {
      "id": "S0206",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 25",
      "audience": "Section 05 · Group 25",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Delhoum Sabrina Zahra",
      "room": "S 14"
    },
    {
      "id": "S0207",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 25",
      "audience": "Section 05 · Group 25",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Madouri Souad",
      "room": "TP 02"
    },
    {
      "id": "S0208",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 25",
      "audience": "Section 05 · Group 25",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Oudjedi Damerdji Linda Fatima",
      "room": "S 13"
    },
    {
      "id": "S0209",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 25",
      "audience": "Section 05 · Group 25",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Alloune Amina",
      "room": "S 13"
    },
    {
      "id": "S0210",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 25",
      "audience": "Section 05 · Group 25",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Saidi Mohammed",
      "room": "S 13"
    },
    {
      "id": "S0211",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": null,
      "audience": "Section 05",
      "day": "Tuesday",
      "time": "08:30-10:00",
      "module": "Algèbre 3",
      "type": "Cours",
      "professor": "Zerkouk Hanene",
      "room": "AMPHI B"
    },
    {
      "id": "S0212",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": null,
      "audience": "Section 05",
      "day": "Tuesday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 3",
      "type": "Cours",
      "professor": "Khelil Ikram",
      "room": "AMPHI B"
    },
    {
      "id": "S0213",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": null,
      "audience": "Section 05",
      "day": "Wednesday",
      "time": "08:30-10:00",
      "module": "Probabilités 2",
      "type": "Cours",
      "professor": "Mostafa Hanchour Kheira",
      "room": "AMPHI B"
    },
    {
      "id": "S0214",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": null,
      "audience": "Section 05",
      "day": "Wednesday",
      "time": "10:00-11:30",
      "module": "Analyse financière",
      "type": "Cours",
      "professor": "Boukssassa Souhila Kheira",
      "room": "AMPHI B"
    },
    {
      "id": "S0215",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 25",
      "audience": "Section 05 · Group 25",
      "day": "Wednesday",
      "time": "13:00-14:30",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "Benamara Dalila",
      "room": "S 09"
    },
    {
      "id": "S0216",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 25",
      "audience": "Section 05 · Group 25",
      "day": "Wednesday",
      "time": "14:30-16:00",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "SI DJILANI",
      "room": "S 09"
    },
    {
      "id": "S0217",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": null,
      "audience": "Section 05",
      "day": "Thursday",
      "time": "08:30-10:00",
      "module": "Géographie économique",
      "type": "Cours",
      "professor": "Benamira Nouara",
      "room": "AMPHI B"
    },
    {
      "id": "S0218",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": null,
      "audience": "Section 05",
      "day": "Thursday",
      "time": "10:00-11:30",
      "module": "Microéconomie 1",
      "type": "Cours",
      "professor": "Saidi Mohammed",
      "room": "AMPHI B"
    },
    {
      "id": "S0219",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 26",
      "audience": "Section 05 · Group 26",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Laadjal Chaimaa",
      "room": "S 15"
    },
    {
      "id": "S0220",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 26",
      "audience": "Section 05 · Group 26",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Français 3",
      "type": "Td",
      "professor": "Belkacem Fatima Zohra",
      "room": "S 15"
    },
    {
      "id": "S0221",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 26",
      "audience": "Section 05 · Group 26",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Hakiki Saliha",
      "room": "TP 01"
    },
    {
      "id": "S0222",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 26",
      "audience": "Section 05 · Group 26",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Amir Samir",
      "room": "S 04"
    },
    {
      "id": "S0223",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 26",
      "audience": "Section 05 · Group 26",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Zerkouk Hanene",
      "room": "S 17"
    },
    {
      "id": "S0224",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 26",
      "audience": "Section 05 · Group 26",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Oudjedi Damerdji Linda Fatima",
      "room": "S 17"
    },
    {
      "id": "S0225",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 26",
      "audience": "Section 05 · Group 26",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "Halima Rahim",
      "room": "S 15"
    },
    {
      "id": "S0226",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 26",
      "audience": "Section 05 · Group 26",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Derouiche",
      "room": "S 15"
    },
    {
      "id": "S0227",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 27",
      "audience": "Section 05 · Group 27",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Djemai Samira",
      "room": "S 09"
    },
    {
      "id": "S0228",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 27",
      "audience": "Section 05 · Group 27",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Français 3",
      "type": "Td",
      "professor": "Mokhtari Latifa",
      "room": "S 09"
    },
    {
      "id": "S0229",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 27",
      "audience": "Section 05 · Group 27",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Amir Samir",
      "room": "SC 01"
    },
    {
      "id": "S0230",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 27",
      "audience": "Section 05 · Group 27",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Mostafa Hanchour Kheira",
      "room": "S 15"
    },
    {
      "id": "S0231",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 27",
      "audience": "Section 05 · Group 27",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Hakiki Saliha",
      "room": "TP 02"
    },
    {
      "id": "S0232",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 27",
      "audience": "Section 05 · Group 27",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "MERKIK",
      "room": "S 07"
    },
    {
      "id": "S0233",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 27",
      "audience": "Section 05 · Group 27",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Khelil Chahine",
      "room": "S 07"
    },
    {
      "id": "S0234",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 27",
      "audience": "Section 05 · Group 27",
      "day": "Wednesday",
      "time": "13:00-14:30",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Abdellah",
      "room": "S 06"
    },
    {
      "id": "S0235",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 28",
      "audience": "Section 05 · Group 28",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Bouteraa",
      "room": "S 05"
    },
    {
      "id": "S0236",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 28",
      "audience": "Section 05 · Group 28",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Laadjal Chaimaa",
      "room": "S 11"
    },
    {
      "id": "S0237",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 28",
      "audience": "Section 05 · Group 28",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "MATH 2",
      "room": "SC 02"
    },
    {
      "id": "S0238",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 28",
      "audience": "Section 05 · Group 28",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Merras Mohammed",
      "room": "S 16"
    },
    {
      "id": "S0239",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 28",
      "audience": "Section 05 · Group 28",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Madouri Souad",
      "room": "TP 03"
    },
    {
      "id": "S0240",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 28",
      "audience": "Section 05 · Group 28",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Français 3",
      "type": "Td",
      "professor": "Mazouzi Samia",
      "room": "S 08"
    },
    {
      "id": "S0241",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 28",
      "audience": "Section 05 · Group 28",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "MERKIK",
      "room": "S 08"
    },
    {
      "id": "S0242",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 28",
      "audience": "Section 05 · Group 28",
      "day": "Wednesday",
      "time": "13:00-14:30",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "SI DJILANI",
      "room": "S 07"
    },
    {
      "id": "S0243",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 29",
      "audience": "Section 05 · Group 29",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Français 3",
      "type": "Td",
      "professor": "Belkacem Fatima Zohra",
      "room": "S 17"
    },
    {
      "id": "S0244",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 29",
      "audience": "Section 05 · Group 29",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "MATH 2",
      "room": "S 17"
    },
    {
      "id": "S0245",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 29",
      "audience": "Section 05 · Group 29",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "Bouteraa",
      "room": "S 06"
    },
    {
      "id": "S0246",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 29",
      "audience": "Section 05 · Group 29",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Madouri Souad",
      "room": "TP 03"
    },
    {
      "id": "S0247",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 29",
      "audience": "Section 05 · Group 29",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Hammouche",
      "room": "S 05"
    },
    {
      "id": "S0248",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 29",
      "audience": "Section 05 · Group 29",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "Mostafa Hanchour Kheira",
      "room": "S 06"
    },
    {
      "id": "S0249",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 29",
      "audience": "Section 05 · Group 29",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Djemai Samira",
      "room": "S 06"
    },
    {
      "id": "S0250",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 29",
      "audience": "Section 05 · Group 29",
      "day": "Wednesday",
      "time": "13:00-14:30",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "Blaha",
      "room": "S 08"
    },
    {
      "id": "S0251",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 30",
      "audience": "Section 05 · Group 30",
      "day": "Sunday",
      "time": "08:30-10:00",
      "module": "Analyse mathématiques 3",
      "type": "Td",
      "professor": "MATH 2",
      "room": "S 18"
    },
    {
      "id": "S0252",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 30",
      "audience": "Section 05 · Group 30",
      "day": "Sunday",
      "time": "10:00-11:30",
      "module": "Anglais 3",
      "type": "Td",
      "professor": "Amir Samir",
      "room": "S 18"
    },
    {
      "id": "S0253",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 30",
      "audience": "Section 05 · Group 30",
      "day": "Sunday",
      "time": "13:00-14:30",
      "module": "Microéconomie 1",
      "type": "Td",
      "professor": "Djemai Samira",
      "room": "S 20"
    },
    {
      "id": "S0254",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 30",
      "audience": "Section 05 · Group 30",
      "day": "Sunday",
      "time": "14:30-16:00",
      "module": "Analyse financière",
      "type": "Td",
      "professor": "MERKIK",
      "room": "S 05"
    },
    {
      "id": "S0255",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 30",
      "audience": "Section 05 · Group 30",
      "day": "Monday",
      "time": "08:30-10:00",
      "module": "Algèbre 3",
      "type": "Td",
      "professor": "Alloune Amina",
      "room": "S 18"
    },
    {
      "id": "S0256",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 30",
      "audience": "Section 05 · Group 30",
      "day": "Monday",
      "time": "10:00-11:30",
      "module": "Probabilités 2",
      "type": "Td",
      "professor": "MATH 1",
      "room": "S 18"
    },
    {
      "id": "S0257",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 30",
      "audience": "Section 05 · Group 30",
      "day": "Monday",
      "time": "13:00-14:30",
      "module": "Informatique 3",
      "type": "Tp",
      "professor": "Hakiki Saliha",
      "room": "TP 02"
    },
    {
      "id": "S0258",
      "level": "Second Year Preparatory Cycle",
      "semester": "Semester 3",
      "section": "Section 05",
      "group": "Group 30",
      "audience": "Section 05 · Group 30",
      "day": "Monday",
      "time": "14:30-16:00",
      "module": "Français 3",
      "type": "Td",
      "professor": "Mazouzi Samia",
      "room": "S 09"
    }
  ]
};
